const puppeteer = require("puppeteer");

// 🔥 PARSER (robust version)
function formatResume(content) {
  if (!content) return "";

  const lines = content.split("<br/>");

  let html = "";
  let inList = false;

  lines.forEach((line) => {
    const trimmed = line.trim();

    if (!trimmed) return; // ✅ skip empty lines

    // 🔹 Section headings
    if (trimmed.endsWith(":")) {
      if (inList) {
        html += "</ul>";
        inList = false;
      }
      html += `<h2>${trimmed.replace(":", "")}</h2>`;
      return;
    }

    // 🔹 Bullet detection (handles "-", " -", "–", etc.)
    if (/^[-–•]\s*/.test(trimmed)) {
      if (!inList) {
        html += "<ul>";
        inList = true;
      }

      html += `<li>${trimmed.replace(/^[-–•]\s*/, "")}</li>`;
      return;
    }

    // 🔹 Normal text
    if (inList) {
      html += "</ul>";
      inList = false;
    }

    html += `<p>${trimmed}</p>`;
  });

  if (inList) html += "</ul>";

  return html;
}

// 🔥 HTML TEMPLATE
function buildHTML(content) {
  return `
  <html>
    <head>
      <style>
        body {
          font-family: Arial, sans-serif;
          padding: 40px;
          line-height: 1.6;
          color: #333;
        }

        .container {
          max-width: 800px;
          margin: auto;
        }

        h1 {
          margin-bottom: 5px;
          font-size: 28px;
        }

        h2 {
          border-bottom: 2px solid #444;
          padding-bottom: 5px;
          margin-top: 20px;
          font-size: 18px;
        }

        p {
          margin: 6px 0;
        }

        ul {
          list-style: none;
          padding-left: 0;
        }

        li::before {
          content: "• ";
          font-weight: bold;
        }

        li {
          margin-bottom: 5px;
        }

        .section {
          margin-top: 15px;
        }

        .header {
          margin-bottom: 15px;
        }

        .title {
          color: #666;
          margin-bottom: 10px;
        }
      </style>
    </head>

    <body>
      <div class="container">

        <div class="header">
          <h1>ATS Optimized Resume</h1>
          <p class="title">Generated by CareerPro</p>
        </div>

        <div class="section">
          ${formatResume(content)}
        </div>

      </div>
    </body>
  </html>`;
}

// 🔥 PDF GENERATOR
async function generatePDF(htmlContent) {
  const browser = await puppeteer.launch({ headless: "new" });
  const page = await browser.newPage();

  await page.setContent(buildHTML(htmlContent), {
    waitUntil: "networkidle0",
  });

  const pdf = await page.pdf({
    format: "A4",
    margin: {
      top: "20mm",
      right: "15mm",
      bottom: "20mm",
      left: "15mm",
    },
    printBackground: true,
  });

  await browser.close();
  return pdf;
}

module.exports = generatePDF;